// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_XoFY5HD6H84yedgaI6c7k7BjRC1gsiE',
    appId: '1:591643758384:web:022b0c7e2a8cfec96102f5',
    messagingSenderId: '591643758384',
    projectId: 'diasterngoapp-4f51a',
    authDomain: 'diasterngoapp-4f51a.firebaseapp.com',
    storageBucket: 'diasterngoapp-4f51a.firebasestorage.app',
    measurementId: 'G-GT9Q6KY74V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrWhZBm92RvOtejXVNnDwPW_odJHUmMs',
    appId: '1:591643758384:android:dde513fb459bce626102f5',
    messagingSenderId: '591643758384',
    projectId: 'diasterngoapp-4f51a',
    storageBucket: 'diasterngoapp-4f51a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnSulcfetpqYptAJ7oU09KJVZakvrCXYs',
    appId: '1:591643758384:ios:8ce3e29ca12a661e6102f5',
    messagingSenderId: '591643758384',
    projectId: 'diasterngoapp-4f51a',
    storageBucket: 'diasterngoapp-4f51a.firebasestorage.app',
    iosBundleId: 'com.example.diasterNgoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnSulcfetpqYptAJ7oU09KJVZakvrCXYs',
    appId: '1:591643758384:ios:8ce3e29ca12a661e6102f5',
    messagingSenderId: '591643758384',
    projectId: 'diasterngoapp-4f51a',
    storageBucket: 'diasterngoapp-4f51a.firebasestorage.app',
    iosBundleId: 'com.example.diasterNgoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_XoFY5HD6H84yedgaI6c7k7BjRC1gsiE',
    appId: '1:591643758384:web:5ca10a7bc25c2fca6102f5',
    messagingSenderId: '591643758384',
    projectId: 'diasterngoapp-4f51a',
    authDomain: 'diasterngoapp-4f51a.firebaseapp.com',
    storageBucket: 'diasterngoapp-4f51a.firebasestorage.app',
    measurementId: 'G-BBW9SQX5YR',
  );
}
